### ISSUE TITLE
Mod causes menu bug

### ISSUE THREAD

**Issue by YnwLNE** [zoom-packers/origins-furs-forge#1]
![image](https://github.com/user-attachments/assets/a4d14803-e5c5-49c8-a5a5-6727a5519105)
[crash-2024-08-04_03.56.11-client.txt](https://github.com/user-attachments/files/16486952/crash-2024-08-04_03.56.11-client.txt)

**Comment by Pandaismyname1** [comment]
Don't forget to install AzureLib

**Comment by YnwLNE** [comment]
> Don't forget to install AzureLib

I had it installed and looked back and for some reason curseforge grabbed the wrong version. It works now, thanks for the heads up and sorry for the useless issue

**Comment by YnwLNE** [comment]
btw are the legs for tail based origins supposed to be invisible?

**Comment by Pandaismyname1** [comment]
Shouldn't be the case. Could you provide a screenshot & the origin used?

Edit: If using Joxta's Medieval Origins resource pack, legs for Siren & Gorgon are disabled by design.

**Comment by YnwLNE** [comment]
After digging around, and assuming it was a mod issue, I found the cause: Just Expressions, Strange I guess since that doesn't affect the full body like its sister pack Fresh Moves but disabling it does fix the leg issue. I am actually using the resource pack (and made a suggestion on its page and tell your friend that they did a great job) but I see that armors leggings and boots still show your otherwise invisible legs 

![2024-08-05_04 34 54](https://github.com/user-attachments/assets/fc700142-3a3c-406d-89e4-3b09e160ffcb)

![2024-08-05_04 32 21](https://github.com/user-attachments/assets/3bf15f36-fb2a-4214-b3e6-93bcc0401696)

![2024-08-05_04 31 52](https://github.com/user-attachments/assets/562a6eef-3a8b-4d8e-a583-768a21438e15)

**Comment by Pandaismyname1** [comment]
Thanks for the heads up, will notify him shortly to remove leggings & boots from the models.

**Comment by Pandaismyname1** [comment]
Shameless plug: I noticed you use Origin classes. Made a resource pack for that. Adds another layer on top for every class (both race & class visible at the same time).
Can be found [here](https://legacy.curseforge.com/minecraft/texture-packs/origin-visuals-classes). Be sure to update the mod to 1.0.2 as well

**Comment by YnwLNE** [comment]
> Shameless plug: I noticed you use Origin classes. Made a resource pack for that. Adds another layer on top for every class (both race & class visible at the same time). Can be found [here](https://legacy.curseforge.com/minecraft/texture-packs/origin-visuals-classes). Be sure to update the mod to 1.0.2 as well

What gave it away? the Fallen Origins requirement? haha. Would gladly use but the link you provided is broke, thanks for the heads up. Is 1.0.2 uploaded? I only see 1.0.1

**Comment by Pandaismyname1** [comment]
They're recently uploaded both mod & resource pack, should be up sometime today I think.

**Comment by YnwLNE** [comment]
Got both, thank you and great work

**Comment by Pandaismyname1** [comment]
> After digging around, and assuming it was a mod issue, I found the cause: Just Expressions, Strange I guess since that doesn't affect the full body like its sister pack Fresh Moves but disabling it does fix the leg issue. I am actually using the resource pack (and made a suggestion on its page and tell your friend that they did a great job) but I see that armors leggings and boots still show your otherwise invisible legs

Version 1.0.5 has been released, fixed this armor piece bug
