### ISSUE TITLE
mod not working on server

### ISSUE THREAD

**Issue by jaffieverse** [zoom-packers/origins-furs-forge#2]
hi i’m having a problem with this mod. it works perfectly fine in my modpack in single player, but it doesn’t work at all in the same modpack on a server. could anyone help?

**Comment by Pandaismyname1** [comment]
It's a known issue. I think if you join a single player world and then join multiplayer it should work. If this does not work, please add some more details. 
Will release a fix for the above soon.

**Comment by Pandaismyname1** [comment]
An update has been published which fixes this issue. You'll have to wait a bit for them to load on the server though
